name: release docker image

on:
  push:
    tags: [ 'v*' ]

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build JIB container and publish
        shell: bash
        run: |-
          mvn --batch-mode package -Pdocker-release \
              -Djib.to.auth.username=${{ github.actor }} \
              -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
